version: "2"
linters:
  enable:
    - decorder
    - durationcheck
    - errorlint
    - gocyclo
    - gosec
    - importas
    - misspell
    - reassign
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - goconst
    - mnd
  disable:
    - errcheck
    - godot
  settings:
    gocyclo:
      min-complexity: 11
    goconst:
      min-len: 3
      min-occurrences: 3
    mnd:
      ignored-numbers:
        - '0'
        - '1'
        - '2'
        - '10'
        - '100'
        - '1000'
        - '1024'
      ignored-functions:
        - 'time.Second'
        - 'time.Minute'
        - 'time.Hour'
        - 'make'
        - 'append'
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
        text: "G102|G107|G115"
