version: "2"
linters:
  enable:
    - decorder
    - durationcheck
    - errorlint
    - gocyclo
    - godot
    - gosec
    - importas
    - misspell
    - reassign
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
  disable:
    - errcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
