project_name: meshtastic-mqtt-exporter

before:
  hooks:
    - go mod tidy

release:
  github:
    owner: capricornusx
    name: meshtastic-mqtt-exporter
  name_template: '{{.Tag}}'
  prerelease: auto
  make_latest: true
  footer: |
    **Full Changelog**: https://github.com/capricornusx/meshtastic-mqtt-exporter/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## What to do next?

    - Read the [Documentation](https://github.com/capricornusx/meshtastic-mqtt-exporter)
  draft: false
builds:
  - id: embedded
    dir: ./cmd/embedded-hook
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
    ldflags: -s -w -X main.version={{.Version}}
    binary: meshtastic-exporter-embedded
    env:
      - CGO_ENABLED=0
  - id: standalone
    dir: ./cmd/standalone
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
    ldflags: -s -w -X main.version={{.Version}}
    binary: meshtastic-exporter-standalone
    env:
      - CGO_ENABLED=0
archives:
  - id: embedded
    builds:
      - embedded
    name_template: '{{ .ProjectName }}-embedded_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    files:
      - README*
      - docs/mqtt-exporter-embedded.service
      - config.yaml
  - id: standalone
    builds:
      - standalone
    name_template: '{{ .ProjectName }}-standalone_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    files:
      - README*
      - config.yaml
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

dist: dist

signs:
  - cmd: sh
    args:
      - "-c"
      - "echo '{{ .Env.SSH_PRIVATE_KEY }}' > /tmp/ssh_key && chmod 600 /tmp/ssh_key && ssh-keygen -Y sign -n file -f /tmp/ssh_key $artifact && rm /tmp/ssh_key"
    signature: "${artifact}.sig"
    artifacts: checksum

dockers:
  # You can have multiple Docker images.
  - #
    # ID of the image, needed if you want to filter by it later on (e.g. on custom publishers).
    id: meshtastic-mqtt-exporter
    goos: linux
    goarch: amd64
    goamd64: "v1"

    # IDs to filter the binaries/packages.
    ids:
      - embedded
    
    # Extra files to add to the Docker build context
    extra_files:
      - config.yaml

    # Templates of the Docker image names.
    image_templates:
      - "ghcr.io/capricornusx/meshtastic-mqtt-exporter:{{ .Tag }}"
      - "ghcr.io/capricornusx/meshtastic-mqtt-exporter:v{{ .Major }}"
      - "ghcr.io/capricornusx/meshtastic-mqtt-exporter:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/capricornusx/meshtastic-mqtt-exporter:latest"

    # Skips the docker push.
    # Could be useful if you also do draft releases.
    #
    # If set to auto, the release will not be pushed to the Docker repository
    #  in case there is an indicator of a prerelease in the tag, e.g. v1.0.0-rc1.
    #
    # Templates: allowed (since v1.19)
    skip_push: false

    # Path to the Dockerfile (from the project root).
    # Default: 'Dockerfile'
    # "{{ .Env.DOCKERFILE }}"
    dockerfile: docs/Dockerfile

    # Set the "backend" for the Docker pipe.
    # Valid options are: docker, buildx, podman.
    # Podman is a GoReleaser Pro feature and is only available on Linux.
    # Default: 'docker'
    use: buildx

    # Docker build flags. Templates: allowed
    build_flag_templates:
      # - --pull
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.version={{.Version }}
      - --label=org.opencontainers.image.description="MQTT telemetry data exporter for Meshtastic"
      - --label=org.opencontainers.image.url=https://github.com/capricornusx/meshtastic-mqtt-exporter
      - --label=org.opencontainers.image.source=https://github.com/capricornusx/meshtastic-mqtt-exporter
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.licenses=MIT
      # - "--platform=linux/amd64/v3"

    # Extra flags to be passed down to the push command.
    push_flags:
      - --tls-verify=false

# https://goreleaser.com/customization/nfpm/
nfpms:
  - package_name: meshtastic-mqtt-exporter
    homepage: https://github.com/capricornusx/meshtastic-mqtt-exporter
    maintainer: Dmitry Dubinin <capricornusx@gmail.com>
    description: |-
      MQTT telemetry data exporter for Meshtastic
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - archlinux
