version: 2

project_name: meshtastic-mqtt-exporter

env:
  - SHORT_NAME=mqtt-exporter

before:
  hooks:
    - go mod tidy

release:
  github:
    owner: capricornusx
    name: '{{ .ProjectName }}'
  name_template: '{{.Tag}}'
  prerelease: auto
  make_latest: true
  footer: |
    **Full Changelog**: https://github.com/capricornusx/{{ .ProjectName }}/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## What to do next?

    - Read the [Documentation](https://github.com/capricornusx/{{ .ProjectName }})
  draft: false

builds:
  - id: embedded
    dir: ./cmd/embedded-hook
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ldflags: -s -w -X main.version={{.Version}}
    binary: '{{ .Env.SHORT_NAME }}-embedded'
    env:
      - CGO_ENABLED=0
  - id: standalone
    dir: ./cmd/standalone
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ldflags: -s -w -X main.version={{.Version}}
    binary: '{{ .Env.SHORT_NAME }}-standalone'
    env:
      - CGO_ENABLED=0

archives:
  - id: embedded
    name_template: '{{ .Env.SHORT_NAME }}-embedded_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - README*
      - docs/mqtt-exporter-embedded.service
      - config.yaml
  - id: standalone
    name_template: '{{ .Env.SHORT_NAME }}-standalone_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - README*
      - config.yaml

checksum:
  name_template: '{{ .Env.SHORT_NAME }}_{{ .Version }}_checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

dist: dist

signs:
  - cmd: sh
    args:
      - "-c"
      - "echo '{{ .Env.SSH_PRIVATE_KEY }}' > /tmp/ssh_key && chmod 600 /tmp/ssh_key && ssh-keygen -Y sign -n file -f /tmp/ssh_key $artifact && rm /tmp/ssh_key"
    signature: "${artifact}.sig"
    artifacts: checksum

dockers:
  - id: meshtastic-mqtt-exporter
    goos: linux
    goarch: amd64
    goamd64: "v1"
    ids:
      - embedded
    extra_files:
      - config.yaml
    image_templates:
      - "ghcr.io/capricornusx/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/capricornusx/{{ .ProjectName }}:v{{ .Major }}"
      - "ghcr.io/capricornusx/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/capricornusx/{{ .ProjectName }}:latest"
    skip_push: false
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.version={{.Version }}
      - --label=org.opencontainers.image.description="MQTT telemetry data exporter for Meshtastic"
      - --label=org.opencontainers.image.url=https://github.com/capricornusx/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/capricornusx/{{ .ProjectName }}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.licenses=MIT
    push_flags:
      - --tls-verify=false

nfpms:
  - package_name: '{{ .Env.SHORT_NAME }}'
    homepage: https://github.com/capricornusx/{{ .ProjectName }}
    maintainer: Dmitry Dubinin <capricornusx@gmail.com>
    description: |-
      MQTT telemetry data exporter for Meshtastic
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - archlinux