logging:
  level: "debug"  # debug, info, warn, error, fatal

mqtt:
  host: 0.0.0.0
  port: 1883
  allow_anonymous: true
  users:
    - username: "admin"
      password: "admin"
    - username: "monitor"
      password: "monitor"
  tls_config:
    enabled: false
    port: 8883
    cert_file: "certs/server.crt"
    key_file: "certs/server.key"
    ca_file: "certs/ca.crt"
  capabilities:
    maximum_inflight: 1024                    # Максимум неподтвержденных сообщений QoS 1/2 на клиента
    maximum_client_writes_pending: 1000       # Максимум сообщений в очереди клиента
    receive_maximum: 512                      # Максимум concurrent QoS сообщений на клиента
    maximum_qos: 2                            # Максимальный уровень QoS (0, 1, 2)
    retain_available: true                    # Поддержка retain сообщений
    maximum_message_expiry_interval: "24h"    # Время жизни сообщений (24h, 1h, 0 = без ограничений)
    maximum_clients: 1000                     # Максимум одновременных клиентов

# HTTP Hook Server (Prometheus + AlertManager)
hook:
  listen: "0.0.0.0:8100"
  prometheus:
    path: "/metrics"
    metrics_ttl: "10m"
    keep_alive: "60s"  # standalone mode only
    topic:
      # Supports MQTT wildcards + and #
      # "msh/#"           - все сообщения начинающиеся с msh/
      # "msh/+/+/json/+/+"  - только JSON сообщения
      pattern: "msh/+/+/json/#"
      log_all_messages: true  # Логировать все MQTT сообщения, соответствующие pattern
    state_file: "meshtastic_state.json"  # Файл для сохранения состояния метрик
  alertmanager:
    path: "/alerts/webhook"
    # MQTT downlink topic pattern: msh/{region}/{hop_limit}/json/mqtt/
    # Регионы: US, EU_433, EU_868, MY_433...
    mqtt_topic: "msh/MY_433/2/json/mqtt/"
    from_node_id: "!f992bd54"  # bd54 - отправитель алертов
    routing:
      default: # for disable set null or {}
        mode: "broadcast"
      critical:
        mode: "broadcast"       # Send it to all nodes
        show_on_sender: true     # Также отправить direct на отправителя
      warning:
        mode: "direct"          # Send it to admins only
        target_nodes:
          - "!f992bd54"          # bd54
          - "!f992aa24"          # aa24
      info:
        mode: "broadcast"       # Send it to all nodes
