mqtt:
  host: 0.0.0.0  # Listen on all interfaces (:: for IPv6)
  port: 1883
  username: "exporter"
  password: "123"
  tls: false
  allow_anonymous: true
  users:
    - username: "meshtastic"
      password: "mesh456"
    - username: "monitor"
      password: "mon789"
    - username: "admin"
      password: "admin000"

prometheus:
  enabled: true
  host: 0.0.0.0  # Listen on all interfaces (:: for IPv6)
  port: 8100
  metrics_ttl: "4m"

state:
  enabled: true
  file: "meshtastic_state.json"
