groups:
  - name: meshtastic
    rules:
      - alert: MeshtasticExporterDown
        expr: up{job="meshtastic"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Meshtastic exporter is down"
          description: "Cannot scrape metrics from Meshtastic exporter"

      - alert: MeshtasticServiceDown
        expr: meshtastic_exporter_info == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Meshtastic service is not running"
          description: "Service info metric indicates the exporter is not functioning"

      - alert: MeshtasticBatteryCritical
        expr: meshtastic_battery_level_percent < 10
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Node {{ $labels.node_id }} battery critical: {{ $value }}%"
          description: "Battery level is {{ $value }}% - device may shut down soon"

      - alert: MeshtasticBatteryLow
        expr: meshtastic_battery_level_percent < 20 and meshtastic_battery_level_percent >= 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Node {{ $labels.node_id }} battery low: {{ $value }}%"
          description: "Battery level is {{ $value }}% - consider charging"

      - alert: MeshtasticNodeOffline
        expr: (time() - meshtastic_node_last_seen_timestamp) > 1200
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Node {{ $labels.node_id }} offline for 20+ minutes"
          description: "Node {{ $labels.node_id }} last seen {{ $value }}s ago"

      - alert: MeshtasticNodeRestarted
        expr: meshtastic_uptime_seconds < 600
        for: 10m
        labels:
          severity: info
        annotations:
          summary: "Node {{ $labels.node_id }} restarted (uptime: {{ $value }}s)"
          description: "Node uptime is only {{ $value }}s - possible restart or stability issue"

      - alert: MeshtasticLowMessageRate
        expr: sum(rate(meshtastic_messages_total[10m])) by (from_node) < 0.01
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Low message rate from node {{ $labels.from_node }}"
          description: "No messages received from node in 15+ minutes"

      - alert: MeshtasticHighTemperature
        expr: meshtastic_temperature_celsius > 60
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Node {{ $labels.node_id }} high temperature: {{ $value }}°C"
          description: "Temperature is {{ $value }}°C - possible overheating"

      - alert: MeshtasticWeakSignal
        expr: meshtastic_rssi_dbm < -120
        for: 10m
        labels:
          severity: info
        annotations:
          summary: "Node {{ $labels.node_id }} weak signal: {{ $value }}dBm"
          description: "RSSI is {{ $value }}dBm - poor connectivity"

