site_name: Meshtastic MQTT Exporter
site_description: Экспорт телеметрии Meshtastic устройств в метрики Prometheus с интеграцией AlertManager
site_author: capricornusx
site_url: https://capricornusx.github.io/meshtastic-mqtt-exporter/

repo_name: capricornusx/meshtastic-mqtt-exporter
repo_url: https://github.com/capricornusx/meshtastic-mqtt-exporter
edit_uri: edit/main/docs/

# Указываем, что файлы документации находятся в подпапке src
docs_dir: 'src'
site_dir: 'site'

theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
  palette:
    # Светлая тема
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Переключить на темную тему
    # Темная тема
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему

plugins:
  - search:
      lang:
        - ru
        - en


nav:
  - Главная: ru/index.md
  - Быстрый старт: ru/quick-start.md
  - Конфигурация: ru/configuration.md
  - API: ru/api.md

# Расширения Markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/capricornusx
    - icon: fontawesome/brands/telegram
      link: https://t.me/capricornusx

copyright: Copyright &copy; 2025 capricornusx

