name: CI

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'
  pull_request:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          only-new-issues: true

      - name: Test with coverage
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Integration tests
        run: go test -v ./tests/ -timeout 30s

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: capricornusx/meshtastic-mqtt-exporter

      - name: Build examples
        run: make build-examples

      - name: Test examples compile
        run: |
          cd docs/mochi-mqtt-integration && go build .

      - name: Check GoReleaser config
        uses: goreleaser/goreleaser-action@v6.3.0
        with:
          args: check
